---
version: "3.7"

services:
  voyages-mysql:
    image: "mysql:8.0.23"
    platform: "linux/amd64"
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    container_name: "voyages-mysql"
    hostname: "voyages-mysql"
    restart: "on-failure"
    ports:
      - "3306:3306"
    networks:
      - "voyages"
    volumes:
      - "mysql_volume:/var/lib/mysql"
    command: --slow-query-log=ON --long-query-time=3 --slow-query-log-file=/tmp/slow.log
    environment:
      MYSQL_ROOT_PASSWORD: "voyages"
      
  voyages-django:
    image: "voyages-django"
    container_name: "voyages-django"
    hostname: "voyages-django"
    restart: "on-failure"
    networks:
      - "voyages"
    depends_on:
      - "voyages-mysql"
    ports:
      - "8000:8000"
    volumes:
      - "./django/:/srv/voyages-api"
    build:
      context: "."
      dockerfile: "./docker/django/Dockerfile"

  voyages-adminer:
    image: "adminer:latest"
    container_name: "voyages-adminer"
    hostname: "voyages-adminer"
    restart: "on-failure"
    depends_on:
      - "voyages-mysql"
    ports:
      - "8080:8080"
    networks:
      - "voyages"


  voyages-flask:
    image: "voyages-flask"
    container_name: "voyages-flask"
    hostname: "voyages-flask"
    restart: "on-failure"
    networks:
      - "voyages"
    ports:
      - "5000:5000"
    volumes:
      - "./flask/:/srv/voyages-flask"
    build:
      context: "."
      dockerfile: "./docker/flask/Dockerfile"
            
networks:
  voyages:
    driver: "bridge"
    ipam:
      driver: "default"
      config:
        - subnet: "172.20.0.0/16"



volumes:
  mysql_volume: {}