---
version: "3.7"

services:
  voyages-mysql:
    image: "mysql:8.0.33-oracle"
    #platform: "linux/amd64"
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    container_name: "voyages-mysql"
    hostname: "voyages-mysql"
    restart: "on-failure"
    ports:
      - "3306:3306"
    networks:
      - "voyages"
    volumes:
      - "mysql_volume:/var/lib/mysql"
    command: --slow-query-log=ON --long-query-time=3 --slow-query-log-file=/tmp/slow.log
    environment:
      MYSQL_ROOT_PASSWORD: "voyages"

  voyages-solr:
    image: "solr:8.5.2"
    container_name: "voyages-solr"
    hostname: "voyages-solr"
    restart: "on-failure"
    ports:
      - "8983:8983"
    networks:
      - "voyages"
    volumes:
      - "solr_volume:/var/solr"
      - "./solr:/srv/voyages/solr"
    environment:
      SOLR_JAVA_MEM: "-Xms1g -Xmx1g"
    
  voyages-api:
    image: "voyages-api"
    container_name: "voyages-api"
    hostname: "voyages-api"
    restart: "on-failure"
    networks:
      - "voyages"
    depends_on:
      - "voyages-mysql"
    ports:
      - "8000:8000"
    volumes:
      - "./api/:/srv/voyages-api"
    build:
      context: "."
      dockerfile: "./docker/api/Dockerfile"

  voyages-adminer:
    image: "adminer:latest"
    container_name: "voyages-adminer"
    hostname: "voyages-adminer"
    restart: "on-failure"
    depends_on:
      - "voyages-mysql"
    ports:
      - "8080:8080"
    networks:
      - "voyages"

  voyages-stats:
    image: "voyages-stats"
    container_name: "voyages-stats"
    hostname: "voyages-stats"
    restart: "on-failure"
    networks:
      - "voyages"
    ports:
      - "5000:5000"
    volumes:
      - "./stats/:/srv/voyages-stats"
    build:
      context: "."
      dockerfile: "./docker/stats/Dockerfile"

  voyages-networks:
    image: "voyages-networks"
    container_name: "voyages-networks"
    hostname: "voyages-networks"
    restart: "on-failure"
    networks:
      - "voyages"
    ports:
      - "5005:5005"
    volumes:
      - "./networks/:/srv/voyages-networks"
    build:
      context: "."
      dockerfile: "./docker/networks/Dockerfile"

networks:
  voyages:
    driver: "bridge"
    ipam:
      driver: "default"
      config:
        - subnet: "172.20.0.0/16"

volumes:
  mysql_volume: {}
  solr_volume: {}