---
version: "3.7"

services:
  voyages-solr:
    image: "solr:8.5.2"
    container_name: "voyages-solr"
    hostname: "voyages-solr"
    restart: "on-failure"
    ports:
      - "8983:8983"
    networks:
      - "voyages"
    volumes:
      - "solr_volume:/var/solr"
      - "./solr:/srv/dspace-django/solr"
    environment:
      SOLR_JAVA_MEM: "-Xms1g -Xmx1g"

  voyages-postgres:
    image: "postgres:latest"
    container_name: "voyages-postgres"
    hostname: "voyages-postgres"
    networks:
      - "voyages"
    volumes:
       - postgres:/data/postgres
       - ./pg_conf:/docker-entrypoint-initdb.d
    ports:
      - "15432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "voyages"
      PGDATA: "/data/postgres"

  voyages-django:
    image: "voyages-django"
    container_name: "voyages-django"
    hostname: "voyages-django"
    restart: "on-failure"
    networks:
      - "voyages"
    depends_on:
      - "voyages-postgres"
      - "voyages-solr"
    ports:
      - "8000:8000"
    volumes:
      - "./django/:/srv/voyages-api"
    build:
      context: "."
      dockerfile: "./docker/django/Dockerfile"

  voyages-flask:
    image: "voyages-flask"
    container_name: "voyages-flask"
    hostname: "voyages-flask"
    restart: "on-failure"
    networks:
      - "voyages"
    ports:
      - "5000:5000"
    volumes:
      - "./flask/:/srv/voyages-flask"
    build:
      context: "."
      dockerfile: "./docker/flask/Dockerfile"
            
networks:
  voyages:
    driver: "bridge"
    ipam:
      driver: "default"
      config:
        - subnet: "172.20.0.0/16"



volumes:
#per https://github.com/asaikali/docker-compose-postgres/blob/master/README.md
  postgres:
  solr_volume: {}