---
version: "3.7"

services:
  voyages-mysql:
    image: "mysql:latest"
    container_name: "voyages-mysql"
    hostname: "voyages-mysql"
    restart: "on-failure"
    ports:
      - "3306:3306"
    volumes:
      - "mysql_volume:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "voyages"

  voyages-django:
    image: "voyages-django"
    container_name: "voyages-django"
    hostname: "voyages-django"
    restart: "on-failure"
    depends_on:
      - "voyages-mysql"
    ports:
      - "8000:8000"
    volumes:
      - "./src/:/srv/voyages-api"
    build:
      context: "."
      dockerfile: "./docker/django/Dockerfile"

  voyages-flask:
    image: "voyages-flask"
    container_name: "voyages-flask"
    hostname: "voyages-flask"
    restart: "on-failure"
    ports:
      - "5000:5000"
    volumes:
      - "./flask/:/srv/voyages-flask"
    build:
      context: "."
      dockerfile: "./docker/flask/Dockerfile"

  voyages-adminer:
    image: "adminer:latest"
    container_name: "voyages-adminer"
    hostname: "voyages-adminer"
    restart: "on-failure"
    depends_on:
      - "voyages-mysql"
    ports:
      - "8080:8080"

networks:
  default:
    name: voyages

volumes:
  mysql_volume: {}
